name: C/C++ CI

on:
  push:
    branches: [ "https://github.com/Slackes/Fortnite-External" ]
  pull_request:
    branches: [ "https://github.com/Slackes/Fortnite-External" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
        configuration: [debug, release]
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
    - name: configure
      run: |
        ./configure CC=${{ matrix.compiler }} CXX=${{ matrix.compiler }} --enable-${{ matrix.configuration }}
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
